// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

namespace DurableTask.PostgresSQL
{
    using System;
    using System.Diagnostics;
    using System.IO;
    using System.Text;
    using DurableTask.Core;
    using DurableTask.Core.History;
    using Newtonsoft.Json;
    using SemVersion;

    static class DTUtils
    {
        public static readonly SemanticVersion ExtensionVersion = GetExtensionVersion();
        public static readonly string ExtensionVersionString = GetExtensionVersionForLogging(ExtensionVersion);

        // DurableTask.Core has a public static variable that contains the app name
        public static readonly string AppName = DurableTask.Core.Common.Utils.AppName;

        static readonly JsonSerializer DefaultJsonSerializer = JsonSerializer.Create(
            new JsonSerializerSettings
            {
                TypeNameHandling = TypeNameHandling.None,
                NullValueHandling = NullValueHandling.Ignore,
            });

        static SemanticVersion GetExtensionVersion()
        {
            // The product version is auto-generated by the Microsoft.SourceLink.GitHub nuget package.
            // Example: 0.1.0-alpha+46661b102c4ccd123f46782f481c3d4b004e3845
            string productVersion = FileVersionInfo.GetVersionInfo(
                typeof(PostgresOrchestrationService).Assembly.Location).ProductVersion;
            return SemanticVersion.Parse(productVersion);
        }

        static string GetExtensionVersionForLogging(SemanticVersion version)
        {
            var builder = new StringBuilder();
            builder
                .Append(version.Major)
                .Append('.')
                .Append(version.Minor)
                .Append('.')
                .Append(version.Patch);

            if (!string.IsNullOrEmpty(version.Prerelease))
            {
                builder.Append('-').Append(version.Prerelease);
            }

            return builder.ToString();
        }

        public static string SerializeToJson(object value)
        {
            using var writer = new StringWriter();
            DefaultJsonSerializer.Serialize(writer, value);
            return writer.ToString();
        }

        public static T? DeserializeFromJson<T>(string json)
        {
            using var reader = new StringReader(json);
            using var jsonReader = new JsonTextReader(reader);
            return DefaultJsonSerializer.Deserialize<T>(jsonReader);
        }

        public static string EscapeJson(string unescapedJson)
        {
            return JsonConvert.ToString(unescapedJson);
        }

        public static int GetTaskEventId(HistoryEvent e)
        {
            return e switch
            {
                TaskScheduledEvent tse => tse.EventId,
                TaskCompletedEvent tce => tce.TaskScheduledId,
                TaskFailedEvent tfe => tfe.TaskScheduledId,
                SubOrchestrationInstanceCreatedEvent soice => soice.EventId,
                SubOrchestrationInstanceCompletedEvent soice => soice.TaskScheduledId,
                SubOrchestrationInstanceFailedEvent soife => soife.TaskScheduledId,
                TimerCreatedEvent tce => tce.EventId,
                TimerFiredEvent tfe => tfe.TimerId,
                EventSentEvent ese => ese.EventId,
                EventRaisedEvent ere => ere.EventId,
                _ => -1
            };
        }

        public static bool HasPayload(HistoryEvent e)
        {
            return e switch
            {
                ExecutionStartedEvent => true,
                ExecutionCompletedEvent => true,
                ExecutionTerminatedEvent => true,
                TaskScheduledEvent => true,
                TaskCompletedEvent => true,
                TaskFailedEvent => true,
                SubOrchestrationInstanceCreatedEvent => true,
                SubOrchestrationInstanceCompletedEvent => true,
                SubOrchestrationInstanceFailedEvent => true,
                TimerCreatedEvent => false,
                TimerFiredEvent => false,
                EventSentEvent => true,
                EventRaisedEvent => true,
                _ => false
            };
        }
    }
}
